name: Build and Test
permissions: read-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3

      - name: "Run `bazel build`"
        run: |
          bazel build -c opt //...

      - name: "Run `bazel test`"
        run: |
          bazel test -c opt //...

      - name: "Run `bazel test --config=asan`"
        run: |
          bazel test --config=asan //...
